# Generated by assistant on 2025-12-24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('actor', models.CharField(blank=True, max_length=200, null=True, help_text='JWT sub or service key identifier')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, db_index=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='proposal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['action', 'idempotency_key'], name='api_rest_toola_acti_5c5da6_idx')],
            },
        ),
    ]
