# Generated by assistant on 2025-12-24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_toolactionlog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='toolactionlog',
            constraint=models.UniqueConstraint(
                fields=['action', 'idempotency_key'],
                name='unique_action_idempotency',
                condition=models.Q(idempotency_key__isnull=False),
            ),
        ),
    ]
