# Generated by Django 5.2.6 on 2025-10-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_user_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto_perfil',
        ),
    ]
