# Generated by Django 5.2.6 on 2025-10-26 16:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_remove_user_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaservicio',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='reservaservicio',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='reservaservicio',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
