# Generated by Django 5.2.6 on 2025-10-26 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_remove_reservaservicio_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaservicio',
            name='fecha_servicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='hora_servicio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
