# Generated by Django 5.2.6 on 2026-01-17 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('mime', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Partner')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código único')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('webhook_url', models.URLField(verbose_name='URL del Webhook')),
                ('webhook_secret', models.CharField(max_length=64, verbose_name='Secret HMAC compartido')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('api_key', models.CharField(max_length=64, unique=True, verbose_name='API Key del Partner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True, verbose_name='Último webhook enviado')),
            ],
            options={
                'verbose_name': 'Partner B2B',
                'verbose_name_plural': 'Partners B2B',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(help_text='ID único de la transacción en la pasarela', max_length=100, unique=True, verbose_name='ID de Referencia')),
                ('provider', models.CharField(choices=[('mock', 'Mock (Testing)'), ('stripe', 'Stripe'), ('mercadopago', 'MercadoPago'), ('payu', 'PayU'), ('manual', 'Manual')], max_length=20, verbose_name='Proveedor de Pago')),
                ('event', models.CharField(choices=[('payment.pending', 'Pago Pendiente'), ('payment.success', 'Pago Exitoso'), ('payment.failed', 'Pago Fallido'), ('payment.refunded', 'Pago Reembolsado'), ('payment.cancelled', 'Pago Cancelado')], default='payment.pending', max_length=30, verbose_name='Evento de pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del cliente')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del cliente')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata adicional')),
                ('raw_webhook_data', models.JSONField(blank=True, default=dict, verbose_name='Datos crudos del webhook')),
                ('webhook_event_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de evento webhook original')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='Tipo de evento')),
                ('payload', models.JSONField(verbose_name='Payload enviado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('failed', 'Fallido'), ('retrying', 'Reintentando')], default='pending', max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='Código HTTP')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='Respuesta')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('attempts', models.IntegerField(default=0, verbose_name='Intentos realizados')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='Máximo de intentos')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Próximo reintento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
            ],
            options={
                'verbose_name': 'Entrega de Webhook',
                'verbose_name_plural': 'Entregas de Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outgoing', 'Saliente'), ('incoming', 'Entrante')], max_length=10)),
                ('event_type', models.CharField(max_length=50, verbose_name='Tipo de evento')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('headers', models.JSONField(default=dict, verbose_name='Headers HTTP')),
                ('signature', models.CharField(blank=True, max_length=128, null=True, verbose_name='Firma HMAC')),
                ('signature_valid', models.BooleanField(default=True, verbose_name='Firma válida')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('processing_result', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de Evento Webhook',
                'verbose_name_plural': 'Logs de Eventos Webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('booking.created', 'Reserva creada'), ('booking.confirmed', 'Reserva confirmada'), ('booking.cancelled', 'Reserva cancelada'), ('booking.completed', 'Reserva completada'), ('payment.success', 'Pago exitoso'), ('payment.failed', 'Pago fallido'), ('payment.refunded', 'Pago reembolsado'), ('service.created', 'Servicio creado'), ('service.updated', 'Servicio actualizado'), ('service.activated', 'Servicio activado'), ('service.deactivated', 'Servicio desactivado'), ('order.created', 'Orden creada (partner)'), ('tour.purchased', 'Tour comprado (partner)')], max_length=50, verbose_name='Tipo de evento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscripción a Webhook',
                'verbose_name_plural': 'Suscripciones a Webhooks',
                'ordering': ['partner', 'event_type'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='toolactionlog',
            name='unique_action_idempotency',
        ),
        migrations.RenameIndex(
            model_name='toolactionlog',
            new_name='api_rest_to_action_d11d0a_idx',
            old_name='api_rest_toola_acti_5c5da6_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api_rest.cliente'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='api_rest.reserva', verbose_name='Reserva asociada'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api_rest.partner'),
        ),
        migrations.AddField(
            model_name='webhookeventlog',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='api_rest.partner'),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api_rest.partner'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference_id'], name='api_rest_pa_referen_9f726e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'status'], name='api_rest_pa_provide_d0a6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reserva', 'status'], name='api_rest_pa_reserva_a6c9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventlog',
            index=models.Index(fields=['event_type', 'created_at'], name='api_rest_we_event_t_319c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventlog',
            index=models.Index(fields=['partner', 'direction'], name='api_rest_we_partner_52f09e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webhooksubscription',
            unique_together={('partner', 'event_type')},
        ),
    ]
