# Generated by Django 5.2.6 on 2026-01-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('mime', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='toolactionlog',
            name='unique_action_idempotency',
        ),
        migrations.RenameIndex(
            model_name='toolactionlog',
            new_name='api_rest_to_action_d11d0a_idx',
            old_name='api_rest_toola_acti_5c5da6_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api_rest.cliente'),
        ),
    ]
