# Generated by Django 5.2.6 on 2025-11-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_reservaservicio_fecha_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50),
        ),
    ]
