# Generated by Django 5.2.6 on 2026-01-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_document_and_more'),
        ('api_rest', '0006_document_partner_paymenttransaction_webhookdelivery_and_more'),
    ]

    operations = [
    ]
