# Generated by Django 5.2.6 on 2026-01-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_merge_20260117_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooksubscription',
            name='event_type',
            field=models.CharField(choices=[('booking.created', 'Reserva creada'), ('booking.confirmed', 'Reserva confirmada'), ('booking.cancelled', 'Reserva cancelada'), ('booking.completed', 'Reserva completada'), ('payment.success', 'Pago exitoso'), ('payment.succeeded', 'Pago exitoso (succeeded)'), ('payment.failed', 'Pago fallido'), ('payment.refunded', 'Pago reembolsado'), ('service.created', 'Servicio creado'), ('service.updated', 'Servicio actualizado'), ('service.activated', 'Servicio activado'), ('service.deactivated', 'Servicio desactivado'), ('adoption.completed', 'Adopción completada'), ('order.created', 'Orden creada (partner)'), ('tour.purchased', 'Tour comprado (partner)')], max_length=50, verbose_name='Tipo de evento'),
        ),
    ]
