"""
Django settings for mi_proyecto project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env (ruta explícita)
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)

# Debug: verificar que se cargó JWT_PUBLIC_KEY
jwt_key = os.environ.get('JWT_PUBLIC_KEY', '')
if jwt_key:
    print(f"✅ JWT_PUBLIC_KEY cargada ({len(jwt_key)} chars)")
else:
    print("⚠️ JWT_PUBLIC_KEY no encontrada en .env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8w--3m7cxoc_h-*1#*w=^q#ru$w6(xbogc8zhp7vtzap^&t*x&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'host.docker.internal', 'kubernetes.docker.internal', '.ngrok-free.dev']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'api_rest',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mi_proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mi_proyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:4000",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-dashboard",  # Permitir header personalizado para dashboard
]

# Media settings for uploaded files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Orchestrator integration
# When running the Orchestrator + Django together, set the following env vars so the
# Orchestrator can call the protected tools endpoints:
# - ORCHESTRATOR_API_KEY on Django (shared secret)
# - ORCHESTRATOR_TOOLS_API_KEY on Orchestrator (same secret)
ORCHESTRATOR_INGEST_URL = os.environ.get('ORCHESTRATOR_INGEST_URL')
ORCHESTRATOR_API_KEY = os.environ.get('ORCHESTRATOR_API_KEY')

# ========================================
# Pilar 4: n8n Event Bus Configuration
# ========================================
# URL base de n8n para webhooks
N8N_WEBHOOK_URL = os.environ.get('N8N_WEBHOOK_URL', 'http://localhost:5678')

# Timeout para llamadas a n8n (segundos)
N8N_TIMEOUT = int(os.environ.get('N8N_TIMEOUT', '10'))

# Habilitar/deshabilitar Event Bus
EVENT_BUS_ENABLED = os.environ.get('EVENT_BUS_ENABLED', 'true').lower() == 'true'

# Partner Integration
PARTNER_WEBHOOK_SECRET = os.environ.get('PARTNER_WEBHOOK_SECRET', 'your-partner-secret')
PARTNER_WEBHOOK_URL = os.environ.get('PARTNER_WEBHOOK_URL', '')

# Payment Gateway Webhooks
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
PAYU_MERCHANT_ID = os.environ.get('PAYU_MERCHANT_ID', '')
PAYU_API_KEY = os.environ.get('PAYU_API_KEY', '')
MERCADOPAGO_ACCESS_TOKEN = os.environ.get('MERCADOPAGO_ACCESS_TOKEN', '')

# Telegram Bot
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')

# WhatsApp Business API
WHATSAPP_VERIFY_TOKEN = os.environ.get('WHATSAPP_VERIFY_TOKEN', '')
WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '')


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api_rest.authentication.ApiKeyAuthentication',
        'api_rest.authentication.JWTAuthentication',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API_REST FINDYOURWORK',
    'DESCRIPTION': 'API REST para la aplicacion FindYourWork',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}

# JWT_PUBLIC_KEY ya se cargó al inicio con load_dotenv(dotenv_path=env_path)
JWT_PUBLIC_KEY = os.environ.get("JWT_PUBLIC_KEY")

if not JWT_PUBLIC_KEY:
    raise RuntimeError("JWT_PUBLIC_KEY no está definida en el entorno. Verifica el archivo .env")
JWT_PUBLIC_KEY = JWT_PUBLIC_KEY.replace("\\n", "\n")

