package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"strconv"

	"github.com/MarlonX-a/5toA_Proyecto_Autonomo_Apps_Ser_web/Golang/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*model.User, error) {
	return r.RESTClient.CreateUser(ctx, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id int32, input model.UserInput) (*model.User, error) {
	return r.RESTClient.UpdateUser(ctx, strconv.Itoa(int(id)), input)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteUser(ctx, strconv.Itoa(int(id)))
}

// CreateUbicacion is the resolver for the createUbicacion field.
func (r *mutationResolver) CreateUbicacion(ctx context.Context, input model.UbicacionInput) (*model.Ubicacion, error) {
	return r.RESTClient.CreateUbicacion(ctx, input)
}

// UpdateUbicacion is the resolver for the updateUbicacion field.
func (r *mutationResolver) UpdateUbicacion(ctx context.Context, id int32, input model.UbicacionInput) (*model.Ubicacion, error) {
	return r.RESTClient.UpdateUbicacion(ctx, strconv.Itoa(int(id)), input)
}

// DeleteUbicacion is the resolver for the deleteUbicacion field.
func (r *mutationResolver) DeleteUbicacion(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteUbicacion(ctx, strconv.Itoa(int(id)))
}

// CreateCliente is the resolver for the createCliente field.
func (r *mutationResolver) CreateCliente(ctx context.Context, input model.ClienteInput) (*model.Cliente, error) {
	return r.RESTClient.CreateCliente(ctx, input)
}

// UpdateCliente is the resolver for the updateCliente field.
func (r *mutationResolver) UpdateCliente(ctx context.Context, id int32, input model.ClienteInput) (*model.Cliente, error) {
	return r.RESTClient.UpdateCliente(ctx, strconv.Itoa(int(id)), input)
}

// DeleteCliente is the resolver for the deleteCliente field.
func (r *mutationResolver) DeleteCliente(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteCliente(ctx, strconv.Itoa(int(id)))
}

// CreateProveedor is the resolver for the createProveedor field.
func (r *mutationResolver) CreateProveedor(ctx context.Context, input model.ProveedorInput) (*model.Proveedor, error) {
	return r.RESTClient.CreateProveedor(ctx, input)
}

// UpdateProveedor is the resolver for the updateProveedor field.
func (r *mutationResolver) UpdateProveedor(ctx context.Context, id int32, input model.ProveedorInput) (*model.Proveedor, error) {
	return r.RESTClient.UpdateProveedor(ctx, strconv.Itoa(int(id)), input)
}

// DeleteProveedor is the resolver for the deleteProveedor field.
func (r *mutationResolver) DeleteProveedor(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteProveedor(ctx, strconv.Itoa(int(id)))
}

// CreateCategoria is the resolver for the createCategoria field.
func (r *mutationResolver) CreateCategoria(ctx context.Context, input model.CategoriaInput) (*model.Categoria, error) {
	return r.RESTClient.CreateCategoria(ctx, input)
}

// UpdateCategoria is the resolver for the updateCategoria field.
func (r *mutationResolver) UpdateCategoria(ctx context.Context, id int32, input model.CategoriaInput) (*model.Categoria, error) {
	return r.RESTClient.UpdateCategoria(ctx, strconv.Itoa(int(id)), input)
}

// DeleteCategoria is the resolver for the deleteCategoria field.
func (r *mutationResolver) DeleteCategoria(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteCategoria(ctx, strconv.Itoa(int(id)))
}

// CreateServicio is the resolver for the createServicio field.
func (r *mutationResolver) CreateServicio(ctx context.Context, input model.ServicioInput) (*model.Servicio, error) {
	return r.RESTClient.CreateServicio(ctx, input)
}

// UpdateServicio is the resolver for the updateServicio field.
func (r *mutationResolver) UpdateServicio(ctx context.Context, id int32, input model.ServicioInput) (*model.Servicio, error) {
	return r.RESTClient.UpdateServicio(ctx, strconv.Itoa(int(id)), input)
}

// DeleteServicio is the resolver for the deleteServicio field.
func (r *mutationResolver) DeleteServicio(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteServicio(ctx, strconv.Itoa(int(id)))
}

// CreateFotoServicio is the resolver for the createFotoServicio field.
func (r *mutationResolver) CreateFotoServicio(ctx context.Context, input model.FotoServicioInput) (*model.FotoServicio, error) {
	return r.RESTClient.CreateFotoServicio(ctx, input)
}

// UpdateFotoServicio is the resolver for the updateFotoServicio field.
func (r *mutationResolver) UpdateFotoServicio(ctx context.Context, id int32, input model.FotoServicioInput) (*model.FotoServicio, error) {
	return r.RESTClient.UpdateFotoServicio(ctx, strconv.Itoa(int(id)), input)
}

// DeleteFotoServicio is the resolver for the deleteFotoServicio field.
func (r *mutationResolver) DeleteFotoServicio(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteFotoServicio(ctx, strconv.Itoa(int(id)))
}

// CreateReserva is the resolver for the createReserva field.
func (r *mutationResolver) CreateReserva(ctx context.Context, input model.ReservaInput) (*model.Reserva, error) {
	return r.RESTClient.CreateReserva(ctx, input)
}

// UpdateReserva is the resolver for the updateReserva field.
func (r *mutationResolver) UpdateReserva(ctx context.Context, id int32, input model.ReservaInput) (*model.Reserva, error) {
	return r.RESTClient.UpdateReserva(ctx, strconv.Itoa(int(id)), input)
}

// DeleteReserva is the resolver for the deleteReserva field.
func (r *mutationResolver) DeleteReserva(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteReserva(ctx, strconv.Itoa(int(id)))
}

// CreateReservaServicio is the resolver for the createReservaServicio field.
func (r *mutationResolver) CreateReservaServicio(ctx context.Context, input model.ReservaServicioInput) (*model.ReservaServicio, error) {
	return r.RESTClient.CreateReservaServicio(ctx, input)
}

// UpdateReservaServicio is the resolver for the updateReservaServicio field.
func (r *mutationResolver) UpdateReservaServicio(ctx context.Context, id int32, input model.ReservaServicioInput) (*model.ReservaServicio, error) {
	return r.RESTClient.UpdateReservaServicio(ctx, strconv.Itoa(int(id)), input)
}

// DeleteReservaServicio is the resolver for the deleteReservaServicio field.
func (r *mutationResolver) DeleteReservaServicio(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteReservaServicio(ctx, strconv.Itoa(int(id)))
}

// CreatePago is the resolver for the createPago field.
func (r *mutationResolver) CreatePago(ctx context.Context, input model.PagoInput) (*model.Pago, error) {
	return r.RESTClient.CreatePago(ctx, input)
}

// UpdatePago is the resolver for the updatePago field.
func (r *mutationResolver) UpdatePago(ctx context.Context, id int32, input model.PagoInput) (*model.Pago, error) {
	return r.RESTClient.UpdatePago(ctx, strconv.Itoa(int(id)), input)
}

// DeletePago is the resolver for the deletePago field.
func (r *mutationResolver) DeletePago(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeletePago(ctx, strconv.Itoa(int(id)))
}

// CreateCalificacion is the resolver for the createCalificacion field.
func (r *mutationResolver) CreateCalificacion(ctx context.Context, input model.CalificacionInput) (*model.Calificacion, error) {
	return r.RESTClient.CreateCalificacion(ctx, input)
}

// UpdateCalificacion is the resolver for the updateCalificacion field.
func (r *mutationResolver) UpdateCalificacion(ctx context.Context, id int32, input model.CalificacionInput) (*model.Calificacion, error) {
	return r.RESTClient.UpdateCalificacion(ctx, strconv.Itoa(int(id)), input)
}

// DeleteCalificacion is the resolver for the deleteCalificacion field.
func (r *mutationResolver) DeleteCalificacion(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteCalificacion(ctx, strconv.Itoa(int(id)))
}

// CreateComentario is the resolver for the createComentario field.
func (r *mutationResolver) CreateComentario(ctx context.Context, input model.ComentarioInput) (*model.Comentario, error) {
	return r.RESTClient.CreateComentario(ctx, input)
}

// UpdateComentario is the resolver for the updateComentario field.
func (r *mutationResolver) UpdateComentario(ctx context.Context, id int32, input model.ComentarioInput) (*model.Comentario, error) {
	return r.RESTClient.UpdateComentario(ctx, strconv.Itoa(int(id)), input)
}

// DeleteComentario is the resolver for the deleteComentario field.
func (r *mutationResolver) DeleteComentario(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteComentario(ctx, strconv.Itoa(int(id)))
}

// CreateServicioUbicacion is the resolver for the createServicioUbicacion field.
func (r *mutationResolver) CreateServicioUbicacion(ctx context.Context, input model.ServicioUbicacionInput) (*model.ServicioUbicacion, error) {
	return r.RESTClient.CreateServicioUbicacion(ctx, input)
}

// UpdateServicioUbicacion is the resolver for the updateServicioUbicacion field.
func (r *mutationResolver) UpdateServicioUbicacion(ctx context.Context, id int32, input model.ServicioUbicacionInput) (*model.ServicioUbicacion, error) {
	return r.RESTClient.UpdateServicioUbicacion(ctx, strconv.Itoa(int(id)), input)
}

// DeleteServicioUbicacion is the resolver for the deleteServicioUbicacion field.
func (r *mutationResolver) DeleteServicioUbicacion(ctx context.Context, id int32) (bool, error) {
	return r.RESTClient.DeleteServicioUbicacion(ctx, strconv.Itoa(int(id)))
}

// Query resolvers (no cambios necesarios, los filtros y paginación ya funcionan)
func (r *queryResolver) Users(ctx context.Context, pagination *model.Pagination) ([]*model.User, error) {
	return r.RESTClient.ListUsers(ctx, pagination)
}

func (r *queryResolver) User(ctx context.Context, id int32) (*model.User, error) {
	return r.RESTClient.GetUser(ctx, strconv.Itoa(int(id)))
}

func (r *queryResolver) Ubicaciones(ctx context.Context, pagination *model.Pagination) ([]*model.Ubicacion, error) {
	return r.RESTClient.ListUbicaciones(ctx, pagination)
}

func (r *queryResolver) Ubicacion(ctx context.Context, id int32) (*model.Ubicacion, error) {
	return r.RESTClient.GetUbicacion(ctx, strconv.Itoa(int(id)))
}

func (r *queryResolver) Clientes(ctx context.Context, pagination *model.Pagination) ([]*model.Cliente, error) {
	return r.RESTClient.ListClientes(ctx, pagination)
}

func (r *queryResolver) Cliente(ctx context.Context, id int32) (*model.Cliente, error) {
	return r.RESTClient.GetCliente(ctx, strconv.Itoa(int(id)))
}

func (r *queryResolver) Proveedores(ctx context.Context, pagination *model.Pagination) ([]*model.Proveedor, error) {
	return r.RESTClient.ListProveedores(ctx, pagination)
}

func (r *queryResolver) Proveedor(ctx context.Context, id int32) (*model.Proveedor, error) {
	return r.RESTClient.GetProveedor(ctx, strconv.Itoa(int(id)))
}

func (r *queryResolver) Categorias(ctx context.Context, pagination *model.Pagination) ([]*model.Categoria, error) {
	return r.RESTClient.ListCategorias(ctx, pagination)
}

func (r *queryResolver) Categoria(ctx context.Context, id int32) (*model.Categoria, error) {
	return r.RESTClient.GetCategoria(ctx, strconv.Itoa(int(id)))
}

func (r *queryResolver) Servicios(ctx context.Context, filter *model.ServicioFilter, pagination *model.Pagination) ([]*model.Servicio, error) {
	return r.RESTClient.ListServicios(ctx, filter, pagination)
}

func (r *queryResolver) Servicio(ctx context.Context, id int32) (*model.Servicio, error) {
	return r.RESTClient.GetServicio(ctx, strconv.Itoa(int(id)))
}

func (r *queryResolver) Reservas(ctx context.Context, filter *model.ReservaFilter, pagination *model.Pagination) ([]*model.Reserva, error) {
	return r.RESTClient.ListReservas(ctx, filter, pagination)
}

func (r *queryResolver) Reserva(ctx context.Context, id int32) (*model.Reserva, error) {
	return r.RESTClient.GetReserva(ctx, strconv.Itoa(int(id)))
}

func (r *queryResolver) Pagos(ctx context.Context, pagination *model.Pagination) ([]*model.Pago, error) {
	return r.RESTClient.ListPagos(ctx, pagination)
}

func (r *queryResolver) Pago(ctx context.Context, id int32) (*model.Pago, error) {
	return r.RESTClient.GetPago(ctx, strconv.Itoa(int(id)))
}

func (r *queryResolver) Calificaciones(ctx context.Context, pagination *model.Pagination) ([]*model.Calificacion, error) {
	return r.RESTClient.ListCalificaciones(ctx, pagination)
}

func (r *queryResolver) Comentarios(ctx context.Context, pagination *model.Pagination) ([]*model.Comentario, error) {
	return r.RESTClient.ListComentarios(ctx, pagination)
}

func (r *queryResolver) ReporteVentas(ctx context.Context, filter *model.ReporteFilter) (*model.ReporteVentas, error) {
	return r.RESTClient.ReporteVentas(ctx, filter)
}

// Las demás resolvers de reportes y métricas las dejamos igual con panic
func (r *queryResolver) ReporteSatisfaccion(ctx context.Context, filter *model.ReporteFilter) ([]*model.ReporteSatisfaccion, error) {
	return r.RESTClient.ReporteSatisfaccion(ctx, filter)
}

func (r *queryResolver) ReporteProveedores(ctx context.Context, filter *model.ReporteFilter) ([]*model.ReporteProveedor, error) {
	return r.RESTClient.ReporteProveedores(ctx, filter)
}

func (r *queryResolver) ReporteClientes(ctx context.Context, filter *model.ReporteFilter) ([]*model.ReporteCliente, error) {
	return r.RESTClient.ReporteClientes(ctx, filter)
}

func (r *queryResolver) MetricasGenerales(ctx context.Context, filter *model.MetricasFilter) (*model.MetricasGenerales, error) {
	return r.RESTClient.MetricasGenerales(ctx, filter)
}

func (r *queryResolver) ServiciosMasPopulares(ctx context.Context, limit *int32) ([]*model.ServicioVendido, error) {
	// Solo usamos el límite como filtro opcional en la función SQL
	resultados, err := r.getServiciosMasVendidos(ctx, nil)
	if err != nil {
		return nil, err
	}

	if limit != nil && int(*limit) < len(resultados) {
		return resultados[:*limit], nil
	}

	return resultados, nil
}

func (r *queryResolver) ProveedoresMejorCalificados(ctx context.Context, limit *int32) ([]*model.ReporteProveedor, error) {
	return r.RESTClient.ProveedoresMejorCalificados(ctx, limit)
}

func (r *queryResolver) ClientesMasActivos(ctx context.Context, limit *int32) ([]*model.ReporteCliente, error) {
	return r.RESTClient.ClientesMasActivos(ctx, limit)
}

func (r *queryResolver) TendenciasVentas(ctx context.Context, filter *model.MetricasFilter) ([]*model.PuntoTendencia, error) {
	return r.RESTClient.TendenciasVentas(ctx, filter)
}

func (r *queryResolver) TendenciasSatisfaccion(ctx context.Context, filter *model.MetricasFilter) ([]*model.PuntoTendencia, error) {
	return r.RESTClient.TendenciasSatisfaccion(ctx, filter)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
