// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

type Calificacion struct {
	ID         int32     `json:"id"`
	Cliente    *Cliente  `json:"cliente"`
	Servicio   *Servicio `json:"servicio"`
	Fecha      time.Time `json:"fecha"`
	Puntuacion int32     `json:"puntuacion"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Categoria struct {
	ID          int32       `json:"id"`
	Nombre      string      `json:"nombre"`
	Descripcion *string     `json:"descripcion,omitempty"`
	CreatedAt   time.Time   `json:"createdAt"`
	UpdatedAt   time.Time   `json:"updatedAt"`
	Servicios   []*Servicio `json:"servicios,omitempty"`
}

type Cliente struct {
	ID             int32           `json:"id"`
	User           *User           `json:"user"`
	Telefono       string          `json:"telefono"`
	Ubicacion      *Ubicacion      `json:"ubicacion,omitempty"`
	CreatedAt      time.Time       `json:"createdAt"`
	UpdatedAt      time.Time       `json:"updatedAt"`
	Reservas       []*Reserva      `json:"reservas,omitempty"`
	Calificaciones []*Calificacion `json:"calificaciones,omitempty"`
	Comentarios    []*Comentario   `json:"comentarios,omitempty"`
}

type Comentario struct {
	ID        int32     `json:"id"`
	Cliente   *Cliente  `json:"cliente"`
	Servicio  *Servicio `json:"servicio"`
	Titulo    string    `json:"titulo"`
	Texto     string    `json:"texto"`
	Respuesta *string   `json:"respuesta,omitempty"`
	Fecha     time.Time `json:"fecha"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type DistribucionCalificacion struct {
	Puntuacion int32   `json:"puntuacion"`
	Cantidad   int32   `json:"cantidad"`
	Porcentaje float64 `json:"porcentaje"`
}

type FotoServicio struct {
	ID          int32     `json:"id"`
	Servicio    *Servicio `json:"servicio"`
	URLFoto     string    `json:"urlFoto"`
	Descripcion *string   `json:"descripcion,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type MetricasGenerales struct {
	TotalUsuarios        int32           `json:"totalUsuarios"`
	TotalClientes        int32           `json:"totalClientes"`
	TotalProveedores     int32           `json:"totalProveedores"`
	TotalServicios       int32           `json:"totalServicios"`
	TotalReservas        int32           `json:"totalReservas"`
	IngresosTotales      decimal.Decimal `json:"ingresosTotales"`
	PromedioSatisfaccion decimal.Decimal `json:"promedioSatisfaccion"`
}

type Pagination struct {
	Limit  *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
}

type Pago struct {
	ID         int32           `json:"id"`
	Reserva    *Reserva        `json:"reserva"`
	MetodoPago string          `json:"metodoPago"`
	Monto      decimal.Decimal `json:"monto"`
	Estado     string          `json:"estado"`
	Referencia *string         `json:"referencia,omitempty"`
	FechaPago  *time.Time      `json:"fechaPago,omitempty"`
	CreatedAt  time.Time       `json:"createdAt"`
	UpdatedAt  time.Time       `json:"updatedAt"`
}

type Proveedor struct {
	ID          int32       `json:"id"`
	User        *User       `json:"user"`
	Telefono    string      `json:"telefono"`
	Descripcion *string     `json:"descripcion,omitempty"`
	Ubicacion   *Ubicacion  `json:"ubicacion,omitempty"`
	CreatedAt   time.Time   `json:"createdAt"`
	UpdatedAt   time.Time   `json:"updatedAt"`
	Servicios   []*Servicio `json:"servicios,omitempty"`
}

type PuntoTendencia struct {
	Fecha    string          `json:"fecha"`
	Valor    decimal.Decimal `json:"valor"`
	Etiqueta *string         `json:"etiqueta,omitempty"`
}

type Query struct {
}

type ReporteCliente struct {
	Cliente            *Cliente        `json:"cliente"`
	TotalReservas      int32           `json:"totalReservas"`
	GastoTotal         decimal.Decimal `json:"gastoTotal"`
	PromedioPorReserva decimal.Decimal `json:"promedioPorReserva"`
	UltimaReserva      *time.Time      `json:"ultimaReserva,omitempty"`
}

type ReporteProveedor struct {
	Proveedor            *Proveedor      `json:"proveedor"`
	TotalServicios       int32           `json:"totalServicios"`
	IngresosTotales      decimal.Decimal `json:"ingresosTotales"`
	PromedioCalificacion float64         `json:"promedioCalificacion"`
	ServiciosActivos     int32           `json:"serviciosActivos"`
}

type ReporteSatisfaccion struct {
	Servicio                   *Servicio                   `json:"servicio"`
	PromedioCalificacion       float64                     `json:"promedioCalificacion"`
	TotalCalificaciones        int32                       `json:"totalCalificaciones"`
	DistribucionCalificaciones []*DistribucionCalificacion `json:"distribucionCalificaciones"`
}

type ReporteVentas struct {
	Periodo              string             `json:"periodo"`
	TotalVentas          decimal.Decimal    `json:"totalVentas"`
	CantidadReservas     int32              `json:"cantidadReservas"`
	PromedioPorReserva   decimal.Decimal    `json:"promedioPorReserva"`
	ServiciosMasVendidos []*ServicioVendido `json:"serviciosMasVendidos"`
}

type Reserva struct {
	ID            int32              `json:"id"`
	Cliente       *Cliente           `json:"cliente"`
	Fecha         time.Time          `json:"fecha"`
	Hora          string             `json:"hora"`
	Estado        string             `json:"estado"`
	TotalEstimado decimal.Decimal    `json:"totalEstimado"`
	Detalles      []*ReservaServicio `json:"detalles,omitempty"`
	Pagos         []*Pago            `json:"pagos,omitempty"`
	CreatedAt     time.Time          `json:"createdAt"`
	UpdatedAt     time.Time          `json:"updatedAt"`
}

type ReservaFilterInput struct {
	ClienteID  *int32  `json:"clienteId,omitempty"`
	Estado     *string `json:"estado,omitempty"`
	FechaDesde *string `json:"fechaDesde,omitempty"`
	FechaHasta *string `json:"fechaHasta,omitempty"`
}

type ReservaServicio struct {
	ID             int32           `json:"id"`
	Reserva        *Reserva        `json:"reserva"`
	Servicio       *Servicio       `json:"servicio"`
	Cantidad       int32           `json:"cantidad"`
	PrecioUnitario decimal.Decimal `json:"precioUnitario"`
	Subtotal       decimal.Decimal `json:"subtotal"`
	CreatedAt      time.Time       `json:"createdAt"`
	UpdatedAt      time.Time       `json:"updatedAt"`
}

type Servicio struct {
	ID              int32              `json:"id"`
	Proveedor       *Proveedor         `json:"proveedor"`
	Categoria       *Categoria         `json:"categoria"`
	NombreServicio  string             `json:"nombreServicio"`
	Descripcion     *string            `json:"descripcion,omitempty"`
	Duracion        *string            `json:"duracion,omitempty"`
	RatingPromedio  float64            `json:"ratingPromedio"`
	Precio          decimal.Decimal    `json:"precio"`
	Ubicaciones     []*Ubicacion       `json:"ubicaciones,omitempty"`
	Fotos           []*FotoServicio    `json:"fotos,omitempty"`
	Calificaciones  []*Calificacion    `json:"calificaciones,omitempty"`
	Comentarios     []*Comentario      `json:"comentarios,omitempty"`
	DetallesReserva []*ReservaServicio `json:"detallesReserva,omitempty"`
	CreatedAt       time.Time          `json:"createdAt"`
	UpdatedAt       time.Time          `json:"updatedAt"`
}

type ServicioFilterInput struct {
	SoloMios    *bool    `json:"soloMios,omitempty"`
	ProveedorID *int32   `json:"proveedorId,omitempty"`
	CategoriaID *int32   `json:"categoriaId,omitempty"`
	Ciudad      *string  `json:"ciudad,omitempty"`
	MinRating   *float64 `json:"minRating,omitempty"`
	PrecioMin   *float64 `json:"precioMin,omitempty"`
	PrecioMax   *float64 `json:"precioMax,omitempty"`
	Q           *string  `json:"q,omitempty"`
}

type ServicioUbicacion struct {
	ID        int32      `json:"id"`
	Servicio  *Servicio  `json:"servicio"`
	Ubicacion *Ubicacion `json:"ubicacion"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type ServicioVendido struct {
	Servicio          *Servicio       `json:"servicio"`
	CantidadVendida   int32           `json:"cantidadVendida"`
	IngresosGenerados decimal.Decimal `json:"ingresosGenerados"`
}

type TendenciasFilter struct {
	FechaDesde *time.Time `json:"fechaDesde,omitempty"`
	FechaHasta *time.Time `json:"fechaHasta,omitempty"`
}

type Ubicacion struct {
	ID          int32        `json:"id"`
	Direccion   string       `json:"direccion"`
	Ciudad      string       `json:"ciudad"`
	Provincia   string       `json:"provincia"`
	Pais        string       `json:"pais"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
	Clientes    []*Cliente   `json:"clientes,omitempty"`
	Proveedores []*Proveedor `json:"proveedores,omitempty"`
	Servicios   []*Servicio  `json:"servicios,omitempty"`
}

type User struct {
	ID        int32      `json:"id"`
	Username  string     `json:"username"`
	Email     string     `json:"email"`
	FirstName *string    `json:"firstName,omitempty"`
	LastName  *string    `json:"lastName,omitempty"`
	Rol       string     `json:"rol"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	Cliente   *Cliente   `json:"cliente,omitempty"`
	Proveedor *Proveedor `json:"proveedor,omitempty"`
}
